### ISSUE TITLE
configuration & build 

### ISSUE THREAD

**Issue by qnst** [temcocontrols/T3000Webview#6]
Hi, Alaa

1. i added a new .env file on my local environment with follow settings, does it right? 

    API_URL=https://user-lib.temcocontrols.com
    API_WS_URL=wss://user-lib.temcocontrols.com/ws
    LOCAL_API_URL=http://localhost:9103/api
    LOCAL_API_SECRET_KEY=

2. could you tell me the actual values for different workflows ?
    build.yml, build_debug.yml, release.yml, test.yml

    API_URL: ${{ secrets.API_URL }}
    API_WS_URL: ${{ secrets.API_WS_URL }}
    LOCAL_API_URL: ${{ vars.LOCAL_API_URL }}
    LOCAL_API_SECRET_KEY: ${{ secrets.LOCAL_API_SECRET_KEY }}

3. on my dev environment, i followed the guidelines to build the rust & vue project separately, generated the t3_webview_api.dll , t3_webview_api.dll.lib files, and copied them to the T3000, but the ui updates not working. Fandu informed me that only need to build one dll, it should include the vue front files, could you tell me how to build the dlls for local debugging?

**Comment by alaarihan** [comment]
1- yes, the values are correct
2- these values comes from the github env settings so they are the same as your ( #1 ) except for LOCAL_API_SECRET_KEY.
just an important note when you assign some key to LOCAL_API_SECRET_KEY in UI make sure you assign the same key to API_SECRET_KEY in the API, so you should leave it as it is in the development stage

3- for running the dev mode, you just need to run npm run dev so you will see a URL that you can open in your browser, no need to copy or build the webview dll
for production you can see the build steps in the github workflow of [T3000_Building_Automation_System](https://github.com/temcocontrols/T3000_Building_Automation_System) repo to know how we packaging the whole thing together.

**Comment by qnst** [comment]
i got it, thanks for your help
